package com.messenger.chatty.exception;

// for frontend' s exception handling

public enum ErrorDetail {
    UNEXPECTED_NOT_AUTHENTICATION, NO_SUCH_ELEMENT,
    NOT_AUTHENTICATION,UN_AUTHORIZED,FORBIDDEN,
    INVALID_REQUEST_BODY,DUPLICATED_NAME, INVALID_INVITE_CODE,PASSWORD_INEQUALITY
}
