services:
  springboot:
    image: sh020119/project_backend:latest
    container_name: springboot_container
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    environment:
      SPRING_PROFILES_ACTIVE: deploy
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_RABBITMQ_VIRTUAL_HOST: "/"
    networks:
      - my_network


  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    command: >
      sh -c "rabbitmq-plugins enable --offline rabbitmq_stomp &&
             rabbitmq-server"
    networks:
      - my_network


volumes:
  rabbitmq_data:

networks:
  my_network: