# environment variables must be in .env file of root directory
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:3306/chatty_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${LOCAL_MYSQL_USERNAME}
    password: ${LOCAL_MYSQL_PASSWORD}

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true

  jpa:
    hibernate:
      ddl-auto: update # according to our dev environment

  data:
    mongodb:
      uri: mongodb://localhost:27017/chatty_db

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${LOCAL_GOOGLE_CLIENT_ID}
            client-secret: ${LOCAL_GOOGLE_CLIENT_SECRET}
            redirect-uri: ${LOCAL_GOOGLE_REDIRECT_URI}
          github:
            client-id: ${LOCAL_GITHUB_CLIENT_ID}
            client-secret: ${LOCAL_GITHUB_CLIENT_SECRET}
            redirect-uri: ${LOCAL_GITHUB_REDIRECT_URI}


variables:
  cloud:
    s3:
      bucketName:  ${LOCAL_S3_BUCKET_NAME}
      accessKey: ${LOCAL_S3_ACCESS_KEY}
      secretKey: ${LOCAL_S3_SECRET_KEY}
  jwt:
    KEY: ${LOCAL_JWT_SECRET_KEY}
  invitation:
    KEY: ${LOCAL_INVITATION_SECRET_KEY}
  password:
    KEY: ${LOCAL_PASSWORD_SECRET_KEY}

mongodb:
  client: mongodb://username:password@localhost:27017/chat?authSource=chat
  name: chat
