# common setting
spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true


jwt-variables:
  EXPIRES_ACCESS_TOKEN_MINUTE: 10
  EXPIRES_REFRESH_TOKEN_MINUTE: 10080 # 7 days
  ISSUER: webChatty
  KEY: asdqweafsds123+K3yyy  #   Should only be handled in environment variables later