# environment variables must be in .env file of root directory
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${LOCAL_MYSQL_URL}
    username: ${LOCAL_MYSQL_USERNAME}
    password: ${LOCAL_MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop # according to our dev environment

  data:
    mongodb:
      uri: ${LOCAL_MONGODB_URL}

  rabbitmq:
    host: ${LOCAL_RABBITMQ_HOST}
    port: ${LOCAL_RABBITMQ_PORT}
    username: ${LOCAL_RABBITMQ_USERNAME}
    password: ${LOCAL_RABBITMQ_PASSWORD}
