package com.messenger.chatty.entity;


import jakarta.persistence.*;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

//object should be generated by parameterized constructor
@Entity
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class ChannelJoin extends BaseEntity {

    @Id
    @Column(name = "channel_join_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "channel_id")
    private Channel channel;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "member_id")
    private Member member;

    public ChannelJoin(Channel channel , Member member){
        linkChannel(channel);
        linkMember(member);
    }

    //relation-method
    protected void linkChannel(Channel channel) {
        this.channel = channel;
        channel.getChannelJoins().add(this);
    }

    //relation-method
    protected void linkMember(Member member){
        this.member =member;
        member.getChannelJoins().add(this);
    }
}

