package com.messenger.chatty.entity;


import jakarta.persistence.*;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Entity
@Getter
public class WorkspaceMember extends BaseEntity{ // object should be generated by no args constructor

    @Id
    @Column(name = "workspace_member_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "member_id")
    private Member member;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "workspace_id")
    private Workspace workspace;

    //relation-method
    public void setMember(Member member){
        this.member = member;
        member.getWorkspaceMembers().add(this);
    }

    //relation-method
    public void setWorkspace(Workspace workspace){
        this.workspace =workspace;
        workspace.getWorkspaceMembers().add(this);
    }


}
