package com.messenger.chatty.presentation;

// for frontend' s exception handling

public enum ErrorDetail {
    UNEXPECTED_NOT_AUTHENTICATION, NO_SUCH_ELEMENT,
    UN_AUTHORIZED,FORBIDDEN, INVALID_LOGIN_REQUEST,INVALID_LOGOUT_REQUEST,
    INVALID_REQUEST_BODY,DUPLICATED_NAME,
    INVALID_INVITE_CODE,PASSWORD_INEQUALITY

}
